from __future__ import annotations

from .custom_installers import (
    install_hermes_agent,
    install_jetbrains_toolbox,
    install_npm_global,
    install_oh_my_zsh,
    install_ollama,
    install_standalone_script,
    install_vscode,
    install_yubikey_services,
    install_zsh_and_default,
    oh_my_zsh_installed,
    toolbox_installed,
    vscode_installed,
    zsh_installed,
)
from .flatpak import (
    flathub_configured,
    flatpak_installed,
    install_flatpak,
    install_flatpak_and_flathub,
)
from .models import App
from .native_packages import NATIVE_ITEMS, install_native
from .utils import command_installed, local_bin_command_installed


def apps() -> list[App]:
    return [
        App(
            "flatpak",
            "Flatpak + Flathub",
            "native",
            flathub_configured,
            install_flatpak_and_flathub,
        ),
        App(
            "firefox",
            "Firefox",
            "native",
            NATIVE_ITEMS["firefox"].installed,
            install_native(NATIVE_ITEMS["firefox"]),
        ),
        App(
            "thunderbird",
            "Thunderbird",
            "native",
            NATIVE_ITEMS["thunderbird"].installed,
            install_native(NATIVE_ITEMS["thunderbird"]),
        ),
        App(
            "ghostty",
            "Ghostty",
            "native",
            NATIVE_ITEMS["ghostty"].installed,
            install_native(NATIVE_ITEMS["ghostty"]),
        ),
        App(
            "alacritty",
            "Alacritty",
            "native",
            NATIVE_ITEMS["alacritty"].installed,
            install_native(NATIVE_ITEMS["alacritty"]),
        ),
        App(
            "zsh",
            "ZSH + default shell",
            "native",
            zsh_installed,
            install_zsh_and_default,
        ),
        App(
            "oh-my-zsh",
            "Oh My Zsh",
            "native/script",
            oh_my_zsh_installed,
            install_oh_my_zsh,
        ),
        App(
            "yubikey",
            "YubiKey support",
            "native",
            NATIVE_ITEMS["yubikey"].installed,
            install_yubikey_services,
        ),
        App(
            "steam",
            "Steam",
            "native",
            NATIVE_ITEMS["steam"].installed,
            install_native(NATIVE_ITEMS["steam"]),
        ),
        App(
            "neovim",
            "Neovim",
            "native",
            NATIVE_ITEMS["neovim"].installed,
            install_native(NATIVE_ITEMS["neovim"]),
        ),
        App(
            "onlyoffice",
            "ONLYOFFICE Desktop Editors",
            "flathub",
            flatpak_installed("org.onlyoffice.desktopeditors"),
            install_flatpak("org.onlyoffice.desktopeditors"),
        ),
        App(
            "github-cli",
            "GitHub CLI",
            "native",
            NATIVE_ITEMS["github-cli"].installed,
            install_native(NATIVE_ITEMS["github-cli"]),
        ),
        App(
            "edge",
            "Microsoft Edge",
            "flathub",
            flatpak_installed("com.microsoft.Edge"),
            install_flatpak("com.microsoft.Edge"),
        ),
        App(
            "zed",
            "Zed Editor",
            "flathub",
            flatpak_installed("dev.zed.Zed"),
            install_flatpak("dev.zed.Zed"),
        ),
        App(
            "spotify",
            "Spotify",
            "flathub",
            flatpak_installed("com.spotify.Client"),
            install_flatpak("com.spotify.Client"),
        ),
        App(
            "bitwarden",
            "Bitwarden",
            "flathub",
            flatpak_installed("com.bitwarden.desktop"),
            install_flatpak("com.bitwarden.desktop"),
        ),
        App(
            "mullvad-browser",
            "Mullvad Browser",
            "flathub",
            flatpak_installed("net.mullvad.MullvadBrowser"),
            install_flatpak("net.mullvad.MullvadBrowser"),
        ),
        App(
            "brave",
            "Brave Browser",
            "flathub",
            flatpak_installed("com.brave.Browser"),
            install_flatpak("com.brave.Browser"),
        ),
        App(
            "logseq",
            "Logseq",
            "flathub",
            flatpak_installed("com.logseq.Logseq"),
            install_flatpak("com.logseq.Logseq"),
        ),
        App(
            "keepassxc",
            "KeePassXC",
            "flathub",
            flatpak_installed("org.keepassxc.KeePassXC"),
            install_flatpak("org.keepassxc.KeePassXC"),
        ),
        App(
            "ausweisapp",
            "AusweisApp",
            "flathub",
            flatpak_installed("de.bund.ausweisapp.ausweisapp2"),
            install_flatpak("de.bund.ausweisapp.ausweisapp2"),
        ),
        App(
            "nextcloud",
            "Nextcloud Desktop Client",
            "flathub",
            flatpak_installed("com.nextcloud.desktopclient.nextcloud"),
            install_flatpak("com.nextcloud.desktopclient.nextcloud"),
        ),
        App(
            "vscode",
            "Visual Studio Code",
            "native installer",
            vscode_installed,
            install_vscode,
        ),
        App(
            "jetbrains-toolbox",
            "JetBrains Toolbox",
            "native installer",
            toolbox_installed,
            install_jetbrains_toolbox,
        ),
        App(
            "uv",
            "uv",
            "native installer",
            local_bin_command_installed("uv"),
            install_standalone_script(
                "https://astral.sh/uv/install.sh", "install-uv.sh"
            ),
        ),
        App(
            "ruff",
            "Ruff",
            "native installer",
            local_bin_command_installed("ruff"),
            install_standalone_script(
                "https://astral.sh/ruff/install.sh", "install-ruff.sh"
            ),
        ),
        App(
            "ty",
            "ty",
            "native installer",
            local_bin_command_installed("ty"),
            install_standalone_script(
                "https://astral.sh/ty/install.sh", "install-ty.sh"
            ),
        ),
        App(
            "ollama",
            "Ollama",
            "native installer",
            command_installed("ollama"),
            install_ollama,
            default_selected=False,
        ),
        App(
            "pi-agent",
            "Pi Agent",
            "native installer",
            command_installed("pi"),
            install_npm_global("@earendil-works/pi-coding-agent"),
            default_selected=False,
        ),
        App(
            "opencode",
            "opencode",
            "native installer",
            command_installed("opencode"),
            install_npm_global("opencode-ai"),
            default_selected=False,
        ),
        App(
            "hermes-agent",
            "Hermes Agent",
            "native installer",
            command_installed("hermes"),
            install_hermes_agent,
            default_selected=False,
        ),
        App(
            "claude-code",
            "Claude Code",
            "native installer",
            command_installed("claude"),
            install_npm_global("@anthropic-ai/claude-code"),
            default_selected=False,
        ),
        App(
            "codex-cli",
            "Codex CLI",
            "native installer",
            command_installed("codex"),
            install_npm_global("@openai/codex"),
            default_selected=False,
        ),
    ]
